import Image from "next/image";
import Link from "next/link";
import { ArrowLeft, ArrowRight, CheckCircle2, MapPinned, ShieldAlert, Smartphone } from "lucide-react";

export type PracticalGuide = {
  title: string; description: string; slug: string; image: string; imageAlt: string; date: string;
  section: string; introduction: string; warning: string; chapters: { title: string; paragraphs: string[]; bullets?: string[] }[];
  example: string; faqs: { question: string; answer: string }[]; sources: { label: string; href: string; note: string }[];
};

export function PracticalGuideArticle({ guide }: { guide: PracticalGuide }) {
  const siteUrl = process.env.NEXT_PUBLIC_APP_URL ?? "https://www.commety.it";
  const articleUrl = `${siteUrl}${guide.slug}`;
  const data = { "@context": "https://schema.org", "@graph": [
    { "@type": "NewsArticle", headline: guide.title, description: guide.description, image: [`${siteUrl}${guide.image}`], datePublished: "2026-09-11T12:00:00+02:00", dateModified: "2026-09-11T12:00:00+02:00", mainEntityOfPage: { "@type": "WebPage", "@id": articleUrl }, inLanguage: "it-IT", articleSection: guide.section, author: { "@type": "Organization", name: "Commety" }, publisher: { "@type": "Organization", name: "Commety", logo: { "@type": "ImageObject", url: `${siteUrl}/logo-commety.png` } } },
    { "@type": "BreadcrumbList", itemListElement: [{ "@type": "ListItem", position: 1, name: "Commety", item: siteUrl }, { "@type": "ListItem", position: 2, name: "News", item: `${siteUrl}/news` }, { "@type": "ListItem", position: 3, name: guide.title, item: articleUrl }] },
    { "@type": "FAQPage", mainEntity: guide.faqs.map((faq) => ({ "@type": "Question", name: faq.question, acceptedAnswer: { "@type": "Answer", text: faq.answer } })) }
  ] };
  return <main className="min-h-screen bg-[#f6f8fc] text-[#0b2858]">
    <header className="border-b border-[#d8e4f2] bg-white/90 backdrop-blur"><div className="mx-auto flex max-w-4xl items-center justify-between px-6 py-5 sm:px-8"><Link href="/" aria-label="Commety"><Image src="/logo-header-cropped.png" alt="Commety" width={150} height={40} className="h-9 w-auto" /></Link><Link href="/news" className="inline-flex items-center gap-2 rounded-xl px-3 py-2 text-sm font-bold text-[#2867ad] hover:bg-[#edf5ff]"><ArrowLeft className="size-4" />Tutte le news</Link></div></header>
    <article><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(data).replace(/</g, "\\u003c") }} />
      <section className="bg-[radial-gradient(circle_at_84%_8%,#2878bd_0%,#0F2D5F_38%,#061735_100%)] px-6 py-16 text-white sm:px-8 sm:py-24"><div className="mx-auto max-w-4xl"><p className="text-sm font-black uppercase tracking-[.18em] text-[#a9d5ff]">Guide Commety · {guide.date}</p><h1 className="mt-5 text-4xl font-black leading-tight tracking-tight sm:text-6xl">{guide.title}</h1><p className="mt-6 max-w-3xl text-xl leading-9 text-white/80">{guide.description}</p><div className="relative mt-10 overflow-hidden rounded-[1.75rem] border border-white/15"><Image src={guide.image} alt={guide.imageAlt} width={1800} height={1013} priority className="h-auto w-full" /></div></div></section>
      <section className="mx-auto max-w-4xl px-6 py-12 sm:px-8 sm:py-16"><div className="rounded-[2rem] border border-[#d5e1ef] bg-white p-7 shadow-[0_18px_45px_rgba(11,40,88,.1)] sm:p-12"><p className="text-xl font-semibold leading-9 text-[#3d5f87]">{guide.introduction}</p><div className="mt-9 rounded-3xl border border-amber-200 bg-amber-50 p-6"><div className="flex gap-4"><ShieldAlert className="mt-1 size-7 shrink-0 text-amber-700" /><div><h2 className="text-xl font-black text-amber-950">Prima regola: sicurezza e rispetto</h2><p className="mt-2 leading-7 text-amber-900/80">{guide.warning}</p></div></div></div>
      {guide.chapters.map((chapter, i) => <section key={chapter.title}><h2 className="mt-12 text-3xl font-black tracking-tight">Capitolo {i + 1}: {chapter.title}</h2>{chapter.paragraphs.map((p) => <p key={p} className="mt-5 text-lg leading-8 text-[#3d5f87]">{p}</p>)}{chapter.bullets && <ul className="mt-7 space-y-4 text-lg leading-8 text-[#3d5f87]">{chapter.bullets.map((b) => <li key={b} className="flex gap-3"><CheckCircle2 className="mt-1.5 size-5 shrink-0 text-[#25875e]" /><span>{b}</span></li>)}</ul>}</section>)}
      <h2 className="mt-12 text-3xl font-black tracking-tight">Un testo pronto da inviare</h2><blockquote className="mt-6 rounded-3xl border-l-4 border-[#2b78bd] bg-[#f2f7fd] p-6 text-lg leading-8 text-[#294e78]">&quot;{guide.example}&quot;</blockquote>
      <section className="mt-12 rounded-[2rem] bg-[linear-gradient(135deg,#061735,#1762a8)] p-7 text-white sm:p-10"><MapPinned className="size-9 text-[#a9d5ff]" /><p className="mt-6 text-sm font-black uppercase tracking-[.18em] text-[#a9d5ff]">Informazione locale in tempo reale</p><h2 className="mt-3 text-3xl font-black">Segnalalo anche su Commety</h2><p className="mt-5 text-lg leading-8 text-white/80">Dopo aver attivato il canale ufficiale, pubblica la posizione su Commety: chi e&apos; vicino puo&apos; vedere il problema sulla mappa, evitarlo e confermare quando la situazione cambia.</p><p className="mt-5 text-lg leading-8 text-white/80">Commety non sostituisce i soccorsi, il Comune o il gestore competente: rende l&apos;informazione locale piu&apos; visibile e utile.</p><Link href="/mappa" className="mt-7 inline-flex items-center gap-2 rounded-2xl bg-[#20a773] px-6 py-3.5 font-black text-white hover:bg-[#2bc18a]"><Smartphone className="size-5" />Segnala su Commety<ArrowRight className="size-5" /></Link></section>
      <section className="mt-14 border-t border-[#d5e1ef] pt-12"><h2 className="text-3xl font-black">Domande frequenti</h2>{guide.faqs.map((faq) => <div key={faq.question} className="mt-7"><h3 className="text-xl font-black">{faq.question}</h3><p className="mt-2 text-lg leading-8 text-[#3d5f87]">{faq.answer}</p></div>)}</section>
      <section className="mt-12 border-t border-[#d5e1ef] pt-10"><h2 className="text-2xl font-black">Fonti ufficiali</h2><ul className="mt-5 space-y-3 text-[#3d5f87]">{guide.sources.map((s) => <li key={s.href}><a className="font-bold text-[#2867ad] underline" href={s.href} target="_blank" rel="noreferrer">{s.label}</a> — {s.note}</li>)}</ul></section><div className="mt-10 rounded-3xl border border-[#d5e1ef] bg-[#f6f8fc] p-5 text-sm leading-6 text-[#647b98]">Guida informativa riferita all&apos;Italia. Canali e competenze possono variare per territorio: verifica sempre i recapiti ufficiali. In caso di pericolo immediato usa i servizi di emergenza.</div></div></section>
    </article></main>;
}
